version: "3.9"
services:
  backend:
    image: adstec/priv:flask-api-arm-v7
    container_name: flask-api-arm-v7
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py

  nginx:
    image: adstec/priv:nginx-service-arm-v7 
    container_name: nginx-service-arm-v7
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  db-volume:
