version: "3.9"
services:
  backend:
    image: adstec/priv:flask-api-amd64
    container_name: flask-api-amd64
    ports:
      - "5000:5000"
      - "4840:4840"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./backend/database/machine-sim.db:/home/iiot-machine-sim/database/machine-sim.db

  nginx:
    image: adstec/priv:nginx-service-amd64
    container_name: nginx-service-amd64
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  db-volume:
