version: "3.9"
services:
  backend:
    build: ./backend
    image: flask-api
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    image: react-app
  nginx:
    build:
      context: .
    image: nginx-service
    ports:
      - "80:80"
    depends_on:
      - backend
